name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-linux
          path: build/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: build/

  package-linux-appimage:
    #if: ${{ github.event.workflow_run.event == 'push' &&
    #  startsWith(github.ref, 'refs/tags/v') }}
    needs: build-linux
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Download linux build artefacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-linux
          path: download/
      - name: Build AppImage
        id: build-appimage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/lib
          mkdir -p AppDir/share/applications
          mkdir -p AppDir/share/icons/hicolor/256x256/
          cp download/bin/Release/GameSaveSyncClient AppDir/usr/bin/
          cp res/GameSaveSyncClient.desktop AppDir/share/applications
          cp res/icon/GameSaveSyncClient.png AppDir/share/icons/hicolor/256x256/
          wget -O linuxdeployqt-x86_64.AppImage \
          https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-x86_64.AppImage
          ./linuxdeployqt-x86_64.AppImage AppDir/usr/bin/GameSaveSyncClient -appimage -bundle-non-qt-libs
          echo "appimage=$(ls GameSaveSyncClient-*-x86_64.AppImage)" >> "$GITHUB_OUTPUT"
      - name: Package AppImage
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: GameSaveSyncClient-Linux-AppImage
          path: ${{ steps.build-appimage.outputs.appimage }}

  package-windows:
    #if: ${{ github.event.workflow_run.event == 'push' &&
    #  startsWith(github.ref, 'refs/tags/v') }}
    needs: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
      - name: Download windows build artefacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-windows
          path: download/
      - name: Build Windows ZIP
        run: |
          mkdir -p deploy
          copy download\bin\Release\GameSaveSyncClient.exe deploy\
          $windeployqt = (Get-ChildItem -Path "${{ steps.install-qt.outputs.Qt6_DIR }}\.." `
              -Recurse -Filter windeployqt.exe | Select-Object -First 1).FullName
          & $windeployqt `
              --release `
              --no-translations `
              --no-opengl-sw `
              --include-soft-plugins `
              --compiler-runtime `
              deploy\GameSaveSyncClient.exe
          7z a GameSaveSyncClient-Windows.zip deploy\*
      - name: Package Windows
        uses: actions/upload-artifact@v4
        with:
          name: GameSaveSyncClient-Windows-ZIP
          path: GameSaveSyncClient-Windows.zip
